import { Link } from 'react-router-dom'

export default function ProfessionalLandingPage() {
  const steps = [['01','Add your photo','Use a clear, full-body photo for the most natural result.'],['02','Choose a garment','Upload the clothing piece you want to try on.'],['03','Meet your new look','AI blends both images into a realistic preview.']]
  return <div>
    <section className="soft-grid overflow-hidden border-b border-[#dfdfd5]"><div className="app-container grid min-h-[680px] items-center gap-12 py-16 lg:grid-cols-[1.05fr_.95fr] lg:py-20">
      <div className="relative z-10 max-w-2xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#ccd7c8] bg-white/70 px-3 py-1.5 text-xs font-bold uppercase tracking-[.14em] text-[#44604c]"><span className="h-2 w-2 rounded-full bg-[#8aba74]"/> AI-powered styling studio</div><h1 className="display-font text-5xl font-extrabold leading-[1.02] tracking-[-.055em] sm:text-6xl lg:text-[76px]">See the fit<br/>before you <span className="text-[#61826a]">commit.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#5a665e]">Turn any outfit into your next look. Upload your photo and a garment, then let our AI create a realistic preview in moments.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/upload" className="btn-primary !px-7 !py-4">Create your first look →</Link><a href="#how-it-works" className="btn-secondary !px-7 !py-4">▶ &nbsp; See how it works</a></div><div className="mt-10 flex flex-wrap gap-6 text-sm font-medium text-[#667269]"><span>✓ No design skills needed</span><span>✓ Ready in seconds</span><span>✓ Private & secure</span></div></div>
      <div className="relative mx-auto w-full max-w-[500px]"><div className="absolute -left-10 top-12 h-48 w-48 rounded-full bg-[#dff08f]/50 blur-3xl"/><div className="surface relative rotate-[2deg] overflow-hidden p-3"><div className="relative aspect-[4/5] overflow-hidden rounded-[18px] bg-gradient-to-br from-[#d5ded3] via-[#eef0e8] to-[#b7c9bc]"><div className="absolute inset-x-0 top-[13%] mx-auto h-20 w-20 rounded-full bg-[#8e6d59] shadow-lg"/><div className="absolute bottom-[-8%] left-1/2 h-[73%] w-[58%] -translate-x-1/2 rounded-t-[45%] bg-[#234d37] shadow-2xl"><div className="absolute left-1/2 top-14 h-[65%] w-[58%] -translate-x-1/2 rounded-t-[40%] bg-[#f0eee7]"/></div><div className="absolute left-4 top-4 rounded-full bg-white/85 px-3 py-1.5 text-xs font-bold">Before</div><div className="absolute bottom-4 right-4 rounded-full bg-[#173f2d] px-3 py-1.5 text-xs font-bold text-white">AI look ✦</div></div></div><div className="absolute -left-6 bottom-14 rounded-2xl bg-white/90 p-4 shadow-xl"><p className="text-xs font-bold text-[#728077]">STYLE MATCH</p><p className="display-font text-2xl font-extrabold text-[#173f2d]">98%</p></div></div>
    </div></section>
    <section id="how-it-works" className="app-container py-20"><div className="mb-10 text-center"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#67816e]">Simple by design</p><h2 className="display-font mt-3 text-3xl font-extrabold tracking-tight sm:text-4xl">From inspiration to visualization</h2></div><div className="grid gap-4 md:grid-cols-3">{steps.map(([n,t,d]) => <div key={n} className="surface p-7"><span className="text-xs font-extrabold text-[#7c9b80]">{n}</span><h3 className="display-font mt-8 text-xl font-bold">{t}</h3><p className="mt-2 leading-7 text-[#68726b]">{d}</p></div>)}</div></section>
  </div>
}
