import { Link } from 'react-router-dom'

export default function ProfessionalLandingPage() {
  const steps = [['01','Add your photo','Use a clear, full-body photo for the most natural result.'],['02','Choose a garment','Upload the clothing piece you want to try on.'],['03','Meet your new look','AI blends both images into a realistic preview.']]
  const features = [
    ['01', 'Fast visualization', 'Explore an outfit in moments without changing clothes, ordering samples, or visiting a fitting room.'],
    ['02', 'Your style, your way', 'Try shirts, dresses, jackets, hoodies, suits, and more using garments you already love.'],
    ['03', 'Easy comparison', 'Compare the original and generated images side by side, then download the looks worth keeping.'],
    ['04', 'Personal wardrobe', 'Save every generation to your private account and revisit your favorite combinations anytime.'],
  ]
  const faqs = [
    ['What kind of photo works best?', 'Use a clear, front-facing photo with your full upper body visible. Natural lighting and a simple background produce the strongest results.'],
    ['Can I try different clothing categories?', 'Yes. The studio supports shirts, T-shirts, hoodies, jackets, suits, and dresses. Select the correct category before generating.'],
    ['How long does a try-on take?', 'Most looks are generated in moments, though processing time can vary depending on image size and service demand.'],
    ['Are my images saved?', 'Your generations appear in My Looks when you are signed in, allowing you to review or remove them later.'],
  ]
  return <div>
    <section className="soft-grid overflow-hidden border-b border-[#dfdfd5]"><div className="app-container grid min-h-[680px] items-center gap-12 py-16 lg:grid-cols-[1.05fr_.95fr] lg:py-20">
      <div className="relative z-10 max-w-2xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#ccd7c8] bg-white/70 px-3 py-1.5 text-xs font-bold uppercase tracking-[.14em] text-[#44604c]"><span className="h-2 w-2 rounded-full bg-[#8aba74]"/> AI-powered styling studio</div><h1 className="display-font text-5xl font-extrabold leading-[1.02] tracking-[-.055em] sm:text-6xl lg:text-[76px]">See the fit<br/>before you <span className="text-[#61826a]">commit.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#5a665e]">Turn any outfit into your next look. Upload your photo and a garment, then let our AI create a realistic preview in moments.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/upload" className="btn-primary !px-7 !py-4">Create your first look →</Link><a href="#how-it-works" className="btn-secondary !px-7 !py-4">▶ &nbsp; See how it works</a></div><div className="mt-10 flex flex-wrap gap-6 text-sm font-medium text-[#667269]"><span>✓ No design skills needed</span><span>✓ Ready in seconds</span><span>✓ Private & secure</span></div></div>
      <div className="relative mx-auto w-full max-w-[500px]"><div className="absolute -left-10 top-12 h-48 w-48 rounded-full bg-[#dff08f]/50 blur-3xl"/><div className="surface relative rotate-[2deg] overflow-hidden p-3"><div className="relative aspect-[4/5] overflow-hidden rounded-[18px] bg-gradient-to-br from-[#d5ded3] via-[#eef0e8] to-[#b7c9bc]"><div className="absolute inset-x-0 top-[13%] mx-auto h-20 w-20 rounded-full bg-[#8e6d59] shadow-lg"/><div className="absolute bottom-[-8%] left-1/2 h-[73%] w-[58%] -translate-x-1/2 rounded-t-[45%] bg-[#234d37] shadow-2xl"><div className="absolute left-1/2 top-14 h-[65%] w-[58%] -translate-x-1/2 rounded-t-[40%] bg-[#f0eee7]"/></div><div className="absolute left-4 top-4 rounded-full bg-white/85 px-3 py-1.5 text-xs font-bold">Before</div><div className="absolute bottom-4 right-4 rounded-full bg-[#173f2d] px-3 py-1.5 text-xs font-bold text-white">AI look ✦</div></div></div><div className="absolute -left-6 bottom-14 rounded-2xl bg-white/90 p-4 shadow-xl"><p className="text-xs font-bold text-[#728077]">STYLE MATCH</p><p className="display-font text-2xl font-extrabold text-[#173f2d]">98%</p></div></div>
    </div></section>
    <section id="how-it-works" className="app-container py-20"><div className="mb-10 text-center"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#67816e]">Simple by design</p><h2 className="display-font mt-3 text-3xl font-extrabold tracking-tight sm:text-4xl">From inspiration to visualization</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-[#68726b]">No complicated measurements or editing tools. DrapeAI turns a simple idea into a visual you can actually use.</p></div><div className="grid gap-4 md:grid-cols-3">{steps.map(([n,t,d]) => <div key={n} className="surface p-7"><span className="text-xs font-extrabold text-[#7c9b80]">{n}</span><h3 className="display-font mt-8 text-xl font-bold">{t}</h3><p className="mt-2 leading-7 text-[#68726b]">{d}</p></div>)}</div></section>

    <section className="border-y border-[#dfe1d9] bg-[#eef1e8]"><div className="app-container grid items-center gap-14 py-20 lg:grid-cols-2 lg:py-24">
      <div className="relative mx-auto w-full max-w-lg"><div className="aspect-square rounded-[32px] bg-[#173f2d] p-5 shadow-2xl shadow-[#173f2d]/15"><div className="relative h-full overflow-hidden rounded-[24px] bg-gradient-to-br from-[#f0e9dd] to-[#b8c8b9]"><div className="absolute left-8 top-8 rounded-full bg-white/90 px-4 py-2 text-xs font-bold text-[#34533e]">OUTFIT PREVIEW</div><div className="absolute bottom-0 left-1/2 h-[82%] w-[58%] -translate-x-1/2 rounded-t-full bg-[#d6ae82]"><div className="absolute bottom-0 left-1/2 h-[73%] w-[115%] -translate-x-1/2 rounded-t-[42%] bg-[#70866e]"/><div className="absolute left-1/2 top-10 h-20 w-20 -translate-x-1/2 rounded-full bg-[#8b634b]"/></div><div className="absolute bottom-5 left-5 right-5 flex items-center justify-between rounded-2xl bg-white/90 p-4 backdrop-blur"><div><p className="text-xs font-bold text-[#7c877f]">CURRENT LOOK</p><p className="font-bold">Sage everyday jacket</p></div><span className="grid h-10 w-10 place-items-center rounded-full bg-[#dff08f] text-lg">+</span></div></div></div><div className="absolute -right-4 -top-5 rounded-2xl bg-white px-5 py-4 shadow-xl"><p className="text-xs font-bold text-[#7a847d]">GENERATED IN</p><p className="display-font mt-1 text-xl font-extrabold">moments</p></div></div>
      <div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#67816e]">More confidence, less guesswork</p><h2 className="display-font mt-4 text-4xl font-extrabold leading-tight tracking-[-.04em] sm:text-5xl">Make better style decisions before you buy.</h2><p className="mt-5 text-lg leading-8 text-[#626e65]">Online inspiration is everywhere, but imagining it on yourself is difficult. DrapeAI closes that gap with a personal preview designed for quick, confident experimentation.</p><div className="mt-8 grid gap-5 sm:grid-cols-2">{features.map(([n,t,d]) => <div key={n} className="border-t border-[#cbd2c8] pt-5"><span className="text-xs font-extrabold text-[#75917a]">{n}</span><h3 className="display-font mt-2 font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-[#6f7971]">{d}</p></div>)}</div></div>
    </div></section>

    <section className="app-container py-20 lg:py-24"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:gap-20"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#67816e]">Designed around you</p><h2 className="display-font mt-4 text-4xl font-extrabold tracking-[-.04em]">A smarter space to explore your style.</h2><p className="mt-5 leading-7 text-[#68726b]">Build a visual wardrobe of ideas for everyday outfits, special occasions, or your next shopping shortlist.</p><Link to="/upload" className="btn-primary mt-7">Open the studio <span aria-hidden="true">&rarr;</span></Link></div><div className="grid gap-4 sm:grid-cols-2"><div className="surface p-7"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#e8efe3] text-[#31543c]">01</span><h3 className="display-font mt-7 text-xl font-bold">Experiment freely</h3><p className="mt-2 leading-7 text-[#6b756e]">Explore colors, cuts, and categories without the pressure of a purchase.</p></div><div className="surface p-7 sm:translate-y-8"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#eef1cf] text-[#526329]">02</span><h3 className="display-font mt-7 text-xl font-bold">Keep your favorites</h3><p className="mt-2 leading-7 text-[#6b756e]">Save successful looks and return when you are ready to decide.</p></div></div></div></section>

    <section className="border-y border-[#dfe1d9] bg-white/60"><div className="app-container py-20"><div className="mx-auto mb-12 max-w-2xl text-center"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#67816e]">Questions, answered</p><h2 className="display-font mt-3 text-4xl font-extrabold tracking-tight">Everything you need to get started</h2></div><div className="mx-auto grid max-w-4xl gap-x-12 md:grid-cols-2">{faqs.map(([q,a]) => <div key={q} className="border-t border-[#dfe1d9] py-6"><h3 className="display-font font-bold text-[#26342b]">{q}</h3><p className="mt-3 text-sm leading-6 text-[#6d776f]">{a}</p></div>)}</div></div></section>

    <section className="app-container py-16 lg:py-20"><div className="relative overflow-hidden rounded-[32px] bg-[#173f2d] px-6 py-16 text-center text-white sm:px-12 lg:py-20"><div className="absolute -left-20 -top-24 h-64 w-64 rounded-full bg-[#8bae74]/20 blur-2xl"/><div className="absolute -bottom-32 -right-16 h-72 w-72 rounded-full bg-[#dff08f]/15 blur-2xl"/><div className="relative"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#cde1bd]">Your virtual fitting room is ready</p><h2 className="display-font mx-auto mt-4 max-w-2xl text-4xl font-extrabold tracking-[-.04em] sm:text-5xl">That outfit you saved? Try it on now.</h2><p className="mx-auto mt-5 max-w-xl leading-7 text-[#c9d5cc]">Upload a photo, choose your garment, and see your next look come together.</p><Link to="/upload" className="mt-8 inline-flex items-center rounded-full bg-[#dff08f] px-7 py-4 font-bold text-[#173f2d] transition hover:-translate-y-1 hover:bg-[#e9f7a9]">Create a look <span className="ml-2" aria-hidden="true">&rarr;</span></Link></div></div></section>

    <footer className="border-t border-[#dfe1d9]"><div className="app-container flex flex-col gap-5 py-8 text-sm text-[#707a72] sm:flex-row sm:items-center sm:justify-between"><div><span className="display-font font-extrabold text-[#173f2d]">Drape<span className="text-[#678f70]">AI</span></span><span className="ml-3">Visualize your style with AI.</span></div><div className="flex gap-6"><Link to="/upload" className="hover:text-[#173f2d]">Studio</Link><Link to="/history" className="hover:text-[#173f2d]">My looks</Link><Link to="/login" className="hover:text-[#173f2d]">Sign in</Link></div></div></footer>
  </div>
}
